// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwNDzfhrpDXByqHwlKfn4R2kQNFvsGSc8',
    appId: '1:456426753772:web:0fff0685aeb854addb5fc9',
    messagingSenderId: '456426753772',
    projectId: 'newsapp-ed2c6',
    authDomain: 'newsapp-ed2c6.firebaseapp.com',
    storageBucket: 'newsapp-ed2c6.firebasestorage.app',
    measurementId: 'G-41DTMZXEHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu7P30vrBYjtY6B_-yumn2sHQRtAM6V9g',
    appId: '1:456426753772:android:382512cd7cd1f84cdb5fc9',
    messagingSenderId: '456426753772',
    projectId: 'newsapp-ed2c6',
    storageBucket: 'newsapp-ed2c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYCR8Q9hCVT9gp6S_-xDxxneDlhIASClY',
    appId: '1:456426753772:ios:53c274e19513d7eadb5fc9',
    messagingSenderId: '456426753772',
    projectId: 'newsapp-ed2c6',
    storageBucket: 'newsapp-ed2c6.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYCR8Q9hCVT9gp6S_-xDxxneDlhIASClY',
    appId: '1:456426753772:ios:53c274e19513d7eadb5fc9',
    messagingSenderId: '456426753772',
    projectId: 'newsapp-ed2c6',
    storageBucket: 'newsapp-ed2c6.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwNDzfhrpDXByqHwlKfn4R2kQNFvsGSc8',
    appId: '1:456426753772:web:56f6014808785bbcdb5fc9',
    messagingSenderId: '456426753772',
    projectId: 'newsapp-ed2c6',
    authDomain: 'newsapp-ed2c6.firebaseapp.com',
    storageBucket: 'newsapp-ed2c6.firebasestorage.app',
    measurementId: 'G-NKJBMH5NBN',
  );
}
